// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/devices": {
            "get": {
                "description": "Returns a list of all connected iOS devices",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "List devices",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.DevicesResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/activate/enable": {
            "post": {
                "description": "Activates the specified iOS device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activation"
                ],
                "summary": "Enable activation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/activated": {
            "get": {
                "description": "Returns whether the device is activated",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "activation"
                ],
                "summary": "Check activation status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/apps/install": {
            "post": {
                "description": "Installs an application from a URL on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Install application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Application IPA URL",
                        "name": "url",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/apps/kill": {
            "post": {
                "description": "Terminates a running application by process ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Kill application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Process ID",
                        "name": "pid",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/apps/list": {
            "get": {
                "description": "Returns a list of applications installed on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "List applications",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/apps/run": {
            "post": {
                "description": "Launches an application on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "apps"
                ],
                "summary": "Run application",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Application bundle identifier",
                        "name": "bundleid",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/devmode": {
            "get": {
                "description": "Returns whether developer mode is enabled on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer"
                ],
                "summary": "Check developer mode status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/devmode/enable": {
            "post": {
                "description": "Enables developer mode on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer"
                ],
                "summary": "Enable developer mode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/erase": {
            "post": {
                "description": "Erases all content and settings from the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Erase device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/image": {
            "get": {
                "description": "Returns whether the developer disk image is mounted",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer"
                ],
                "summary": "Check developer disk image status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/image/enable": {
            "post": {
                "description": "Mounts the developer disk image on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "developer"
                ],
                "summary": "Mount developer disk image",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/pair/enable": {
            "post": {
                "description": "Pairs the device using the provided certificate",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pairing"
                ],
                "summary": "Enable pairing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/paired": {
            "get": {
                "description": "Returns whether the device is paired",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "pairing"
                ],
                "summary": "Check pairing status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/processes": {
            "get": {
                "description": "Returns a list of running processes on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "List processes",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/profiles/add": {
            "post": {
                "description": "Installs a configuration profile on the device",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "Add profile",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Base64 encoded profile",
                        "name": "profile",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.ProfilleAddRequset"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/{udid}/profiles/list": {
            "get": {
                "description": "Returns a list of configuration profiles installed on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "profiles"
                ],
                "summary": "List profiles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/reboot": {
            "post": {
                "description": "Reboots the specified iOS device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "device"
                ],
                "summary": "Reboot device",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/supervise/enable": {
            "post": {
                "description": "Prepares and enables supervision on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supervision"
                ],
                "summary": "Enable supervision",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/supervised": {
            "get": {
                "description": "Returns whether the device is supervised",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "supervision"
                ],
                "summary": "Check supervision status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/wda/kill": {
            "post": {
                "description": "Stops WebDriverAgent on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wda"
                ],
                "summary": "Kill WebDriverAgent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        },
        "/{udid}/wda/run": {
            "post": {
                "description": "Starts WebDriverAgent on the device",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wda"
                ],
                "summary": "Run WebDriverAgent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Device UDID",
                        "name": "udid",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.GenericResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.Device": {
            "type": "object",
            "properties": {
                "ConnectionType": {
                    "type": "string"
                },
                "ProductName": {
                    "type": "string"
                },
                "ProductType": {
                    "type": "string"
                },
                "ProductVersion": {
                    "type": "string"
                },
                "Udid": {
                    "type": "string"
                }
            }
        },
        "main.DevicesResponse": {
            "type": "object",
            "properties": {
                "devices": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.Device"
                    }
                }
            }
        },
        "main.GenericResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "main.ProfilleAddRequset": {
            "type": "object",
            "properties": {
                "b64profile": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "tinyios",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
